version: '3'
services:
  wordpress:
    image: 729372495934.dkr.ecr.eu-west-1.amazonaws.com/wordpress/docker-base:0.0.7
    restart: always
    ports:
      - 8080:80
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PREFIX: wp_
      WP_ENV: development
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
    volumes:
      - ./:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

volumes:
  mysql-data: