version: '3'
services:
  wordpress:
    image: 729372495934.dkr.ecr.eu-west-1.amazonaws.com/wordpress/docker-base:0.0.7
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db.example.com
      DB_PREFIX: wp_
      WP_ENV: production
      WP_HOME: https://example.com
      WP_SITEURL: https://example.com/wp
      CERTS: example.com,www.example.com
      EMAIL: user@example.com
      # Generate your keys here: https://roots.io/salts.html
      AUTH_KEY: generateme
      SECURE_AUTH_KEY: generateme
      LOGGED_IN_KEY: generateme
      NONCE_KEY: generateme
      AUTH_SALT: generateme
      SECURE_AUTH_SALT: generateme
      LOGGED_IN_SALT: generateme
      NONCE_SALT: generateme
    volumes:
      - ./:/var/www/html
